### ISSUE TITLE
I can't play online

### ISSUE THREAD

**Issue by TeknoDev06** [Anuken/MindustryBuilds#8]
when i click join game, this happens
![image](https://user-images.githubusercontent.com/60188877/83901444-7123e480-a763-11ea-8749-2a598f8147a6.png)

java.lang.ClassCastException: arc.util.serialization.JsonValue cannot be cast to mindustry.ui.dialogs.JoinDialog$Server
	at mindustry.ui.dialogs.JoinDialog.setupRemote(JoinDialog.java:106)
	at mindustry.ui.dialogs.JoinDialog.setup(JoinDialog.java:255)
	at mindustry.ui.dialogs.JoinDialog.lambda$new$7(JoinDialog.java:83)
	at arc.scene.ui.Dialog$5.shown(Dialog.java:384)
	at arc.scene.event.VisibilityListener.handle(VisibilityListener.java:11)
	at arc.scene.Element.notify(Element.java:166)
	at arc.scene.Element.fire(Element.java:137)
	at arc.scene.ui.Dialog.show(Dialog.java:415)
	at arc.scene.ui.Dialog.show(Dialog.java:446)
	at arc.scene.ui.Dialog.show(Dialog.java:441)
	at mindustry.ui.fragments.MenuFragment.checkPlay(MenuFragment.java:197)
	at mindustry.ui.fragments.MenuFragment.lambda$null$23(MenuFragment.java:169)
	at mindustry.ui.fragments.MenuFragment.lambda$buttons$32(MenuFragment.java:238)
	at arc.scene.Element.lambda$clicked$2(Element.java:1008)
	at arc.scene.Element$4.clicked(Element.java:1017)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:33)
	at arc.scene.Scene.touchUp(Scene.java:339)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:137)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:111)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:148)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:40)

**Comment by Anuken** [comment]
Don't.

**Comment by TeknoDev06** [comment]
ok also the new update is cool
